apiVersion: v1
kind: Secret
metadata:
  name: cswp-{{PR_NUMBER}}-secret
  namespace: cswp-{{PR_NUMBER}}
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: "d3BwYXNzd29yZDEyMw==" # echo -n "wppassword123" | base64  # this is for the app
  MYSQL_ROOT_PASSWORD: "d3BwYXNzd29yZDEyMw=="
  MYSQL_PASSWORD: "d3BwYXNzd29yZDEyMw=="