
### Deployment Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc
spec:
  selector:
    app.kubernetes.io/app: {{ .Values.appName }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}

---
{{- if .Values.db.enabled -}}
### DB Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}-svc
spec:
  selector:
    app.kubernetes.io/app: {{ .Values.db.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
{{- end}}
---
{{- if .Values.phpmyadmin.enabled -}}
### PMA Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-pma-svc
spec:
  selector:
    app.kubernetes.io/app: {{ .Values.appName }}-pma
  ports:
  - port: {{ .Values.phpmyadmin.servicePort }}
    targetPort: {{ .Values.phpmyadmin.port }}
{{- end }}
