apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: {{ .Values.containerPort }}
        envFrom:
          - configMapRef:
              name: {{ .Values.appName }}-config
          - secretRef:
              name: {{ .Values.appName }}-secret
        env:
        - name: PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
